### PR TITLE
Write pretty json

### PR DESCRIPTION
**Pull request by wlandau**
C.f. https://github.com/r-releases/help/issues/4

### CODE REVIEW

**Comment by wlandau** [comment]
I also want to see if I can fix https://github.com/r-universe/r-releases/actions/runs/8101409449/job/22141605234.

**Comment by wlandau** [comment]
Ah, the problem on Windows was how shell quotes were printed. Reproduced and fixed, as you can see in the results of the last few commits.

**Review by shikokuchuo — APPROVED** [review]

**Comment by shikokuchuo** [comment]
@wlandau I merged this, do you want to tag the release?

**Comment by wlandau** [comment]
Done: https://github.com/r-releases/r.releases.utils/releases/tag/0.0.5. The next version of https://github.com/r-releases/r-releases.r-universe.dev/blob/main/packages.json should look nicer.

**Pull request merged**
